package constant

const (
	TEXTBLACK, BGBLACK = iota + 30, iota + 40
	TEXTRED, BGRED
	TEXTGREEN, BGGREEN
	TEXTYELLOW, BGYELLOW
	TEXTBLUE, BGBLUE
	TEXTPURPLE, BGPURPLE
	TEXTCYAN, BGCYAN
	TEXTWHITE, BGWHITE
)
