# 服务器配置
server:
  address: "0.0.0.0" #服务运行ip
  port: "8088"  #服务运行端口
  secreteKey: "asd$%^&*asdh&^8asd98&(*()dasdasdasda_()werewrkfgjdg" #密钥
  jwtExpireTime: 36000 #token过期时间

# mysql 配置
database:
  address: "10.80.1.66"
  port: "3306"
  name: "bee"
  user: "root"
  password: "Aa123456!"

# redis缓存配置
redis:
  addr: "10.80.1.66:6379"
  password: "Aa123456!"
  db: 1

# 文件上传配置
upload:
  avatar: "./uploads/file/avatar"
  file: "./uploads/file"

# 异步任务配置
machinery:
  broker: "redis://Aa123456!@10.80.1.66:6379"
  default_queue: "machinery_tasks"
  result_backend: "redis://Aa123456!@10.80.1.66:6379"
  results_expire_in: 360000
  redis:
    max_idle: 3
    max_active: 100
    max_idle_timeout: 300
    wait: true
    read_timeout: 15
    write_timeout: 15
    connect_timeout: 15
    normal_tasks_poll_period: 1000
    delayed_tasks_poll_period: 500