# 服务器配置
server:
  address: "0.0.0.0" #服务运行ip
  port: "8088"  #服务运行端口
  secreteKey: "" #密钥
  jwtExpireTime: 36000 #token过期时间
  sslCertificate: ""
  sslCertificateKey: ""

# mysql 配置
database:
  address: ""
  port: "3306"
  name: ""
  user: ""
  password: ""

# redis缓存配置
redis:
  addr: ""
  password: ""
  db: 1

# 文件上传配置
upload:
  avatar: "./uploads/file/avatar"
  file: "./uploads/file"

# 异步任务配置
machinery:
  broker: ""
  default_queue: "machinery_tasks"
  result_backend: ""
  results_expire_in: 360000
  redis:
    max_idle: 3
    max_active: 100
    max_idle_timeout: 300
    wait: true
    read_timeout: 15
    write_timeout: 15
    connect_timeout: 15
    normal_tasks_poll_period: 1000
    delayed_tasks_poll_period: 500